CREATE TABLE rumah(
id int (5) PRIMARY KEY,
nm_rumah VARCHAR (30) NOT NULL,
deskripsi TEXT,
link TEXT,
createdate TIMESTAMP,
createdby int (5) NOT NULL,
FOREIGN KEY (createdby) REFERENCES admin (id)
ON UPDATE CASCADE
ON DELETE CASCADE,
suku int (5) NOT NULL,
FOREIGN KEY (suku) REFERENCES suku (id)
ON UPDATE CASCADE
ON DELETE CASCADE);