--INSERT INTO rumah
--(id, nm_rumah, deskripsi, link, createdate, createdby, suku)
--VALUES(1,'Rumah Gantung', 'Rumah gantung ntt merupakan rumah gantung yang dibuat menggunakan bahan','http://192.168.43.224:8000/wall.jpg',Now(),1,1);
--
--INSERT INTO rumah
--(id, nm_rumah, deskripsi, link, createdate, createdby, suku)
--VALUES(2,'Rumah Atap', 'Rumah atap ntt merupakan rumah gantung yang dibuat menggunakan bahan','http://192.168.43.224:8000/wall.jpg',Now(),1,1);
--
--INSERT INTO rumah
--(id, nm_rumah, deskripsi, link, createdate, createdby, suku)
--VALUES(3,'Rumah Beton', 'Rumah Beton ntt merupakan rumah gantung yang dibuat menggunakan bahan','http://192.168.43.224:8000/wall.jpg',Now(),1,1);