--INSERT INTO musik
--(id, nm_musik, deskripsi, link, createdate, createdby, suku)
--VALUES(1,'Flobamora', 'Musik rakat flobamora merupakan khas karya masyarakat asli ntt','http://192.168.43.224:8000/wall.jpg',Now(),1,1);
--
--INSERT INTO musik
--(id, nm_musik, deskripsi, link, createdate, createdby, suku)
--VALUES(2,'Kewa', 'Musik rakat flobamora merupakan khas karya masyarakat asli ntt','http://192.168.43.224:8000/wall.jpg',Now(),1,1);
--
--INSERT INTO musik
--(id, nm_musik, deskripsi, link, createdate, createdby, suku)
--VALUES(3,'Disco tanah', 'Disco tanah Musik rakat flobamora merupakan khas karya masyarakat asli ntt','http://192.168.43.224:8000/wall.jpg',Now(),1,1);
--
--INSERT INTO musik
--(id, nm_musik, deskripsi, link, createdate, createdby, suku)
--VALUES(4,'Patah Pinggang', 'Patah pinggang Musik rakat flobamora merupakan khas karya masyarakat asli ntt','http://192.168.43.224:8000/wall.jpg',Now(),1,1);