create table suku (
 id VARCHAR (200) NOT NULL PRIMARY KEY,
nm_suku VARCHAR (30) NOT NULL UNIQUE,
deskripsi TEXT ,
link TEXT,
createdate TIMESTAMP,
createdby VARCHAR (200) NOT NULL,
FOREIGN KEY (createdby) REFERENCES admin (id)
ON UPDATE CASCADE
ON DELETE CASCADE);